queries/ruby/rainbow-delimiters.scm, test/highlight/ruby/regular.rb
Ruby doesn't use brackets for logic blocks, so there's not a lot we can do here. But I did what I can. I mostly matched what VS-Code does for Ruby files. The only difference I'm aware of is I also included `do_block` which I think is not TOO bad, and could be useful for deeply nested specs like the example provided.
=> Add Ruby support

doc/rainbow-delimiters.txt, queries/verilog/rainbow-blocks.scm, queries/verilog/rainbow-delimiters.scm, test/highlight/verilog/systemverilog.sv, test/highlight/verilog/verilog.v
This PR adds some support for Verilog and SystemVerilog, both of which are covered by the same Treesitter grammar in Neovim.
`begin` and `end` blocks should be coloured correctly, which are the main blocks in both languages. I've included support for some extra things like bit indexes. Unfortunately, the SystemVerilog grammar is not very reliable at the moment, which can sometimes cause issues with highlighting. I was also unable to get nested expressions like `(a+(a+b))` to highlight fully correctly.
=> Support SystemVerilog and Verilog

lua/rainbow-delimiters/health.lua
Remove the deprecated check health API warnings, see [here](https://neovim.io/doc/user/deprecated.html#_functions).
=> fix(health): remove deprecated API warnings

queries/sql/rainbow-delimiters.scm, test/highlight/sql/regular.sql
=> feat(sql): add support for sql

queries/tsx/rainbow-delimiters.scm
You forgot to add it for typescript react.
Thanks for the good work!
=> TSX: Add support for member expressions, closes #39

queries/janet_simple/rainbow-delimiters.scm, test/highlight/janet_simple/regular.janet
This is an attempt to add support for [Janet](https://janet-lang.org).
The test file (`regular.janet`) seemed to display fine here.
---
On a side note, the [contributing file](https://github.com/HiPhish/rainbow-delimiters.nvim/blob/652345bd1aa333f60c9cbb1259f77155786e5514/CONTRIBUTING.rst) currently mentions:
`:h ts-rainbow-custom-queries`
May be the following is meant since the transition?
`:h rb-delimiters-custom-query`
=> Add Janet support

README.rst, lua/rainbow-delimiters/setup.lua
This permits simple integration with common plugin managers. With [lazy.nvim](https://github.com/folke/lazy.nvim), for example, one could use the following:
```lua
{
'HiPhish/rainbow-delimiters.nvim',
main = 'rainbow-delimiters.setup',
opts = {
strategy = {
[''] = rainbow_delimiters.strategy['global'],
vim = rainbow_delimiters.strategy['local'],
},
query = {
[''] = 'rainbow-delimiters',
lua = 'rainbow-blocks',
},
highlight = {
'RainbowDelimiterRed',
'RainbowDelimiterYellow',
'RainbowDelimiterBlue',
'RainbowDelimiterOrange',
'RainbowDelimiterGreen',
'RainbowDelimiterViolet',
'RainbowDelimiterCyan',
},
},
}
```
Closes #4.
=> Use idiomatic setup function

CONTRIBUTING.rst, doc/rainbow-delimiters.txt
I noticed that `CONTRIBUTING.rst` still said `@intermediate` instead of `@delimiter`.
Also, I remember discussing updating the version number after the big update. I added it here mainly as a reminder, but I can just remove it again if you prefer.
=> Very minor cleanup

queries/html/rainbow-delimiters.scm
I saw a [request to be able to keep the old style html highlighting](https://www.reddit.com/r/neovim/comments/17tiq3a/big_change_to_rainbowdelimitersnvim/) on reddit, so I thought I would add it. Please let me know if you have a better name for it.
=> Add comment on `html-tag-names` queries

lua/rainbow-delimiters/strategy/local.lua, test/highlight/c/regular.c
The previous fix for #59 fixed the first error, but there was another problem. I tracked down the following error to two things:
1. `vim.inspect` has a problem that causes an error on `vim.inspect(tree:root():range())`. Using a table instead fixes this error, i.e., `vim.inspect( {tree:root():range()} )`.
2. The local strategy's `on_attach` had a typo, where we accidentally reset a table that we wanted to keep if it exists. 
This code should fix both of those problems. 
Additionally I added a `#define` statement to the test file for c, since that was what caused this problem to show up (because it creates another tree in the same language in 0.9.4).
=> Bug fix - fixes #59

queries/luadoc/rainbow-delimiters.scm, test/highlight/luadoc/regular.lua
The luadoc parser has a few problems with things it captures weirdly (or doesn't really capture), but we can get good highlighting for most type annotations in Lua with this. 
Note: If you commit this before the update with types, then I can add `luadoc` there. Otherwise, if you commit the types update first, I can rebase this pull request and add the types here.
=> Add luadoc queries

CONTRIBUTING.rst, README.rst, doc/rainbow-delimiters.txt, lua/rainbow-delimiters.lua, lua/rainbow-delimiters.types.lua, lua/rainbow-delimiters/default.lua, lua/rainbow-delimiters/health.lua, lua/rainbow-delimiters/lib.lua, lua/rainbow-delimiters/log.lua, lua/rainbow-delimiters/setup.lua, lua/rainbow-delimiters/stack.lua, lua/rainbow-delimiters/strategy/global.lua, lua/rainbow-delimiters/strategy/local.lua, lua/rainbow-delimiters/strategy/no-op.lua, lua/rainbow-delimiters/util.lua
I added a lot of type information, so we can get proper LSP information when setting up the plugin:
I also made a few other small edits that might be worth discussing. Here is a list of things to think about before this is ready to be committed:
Other notes:
- If you ever do a rewrite, note that it is easier to give types for strings that don't need to be inside `['<name>']` in a Lua table (like `['local']` or `['']`).
- I couldn't figure out a way for the plugin to capture the fact that the type of `vim.g.rainbow_delimiters` should be of type `rainbow_delimiters.config`. So for now a user of the plugin will have to add `---@type rainbow_delimiters.config` before `vim.g.rainbow_delimiters` to get the LSP to work as expected. I have added this to the docs for now, but we can remove it if …
=> Add more LuaLS types for better LSP info

lua/rainbow-delimiters.types.lua, lua/rainbow-delimiters/lib.lua
I wanted to fix a `[integer]` typo to `[string]` in the new priority types, and thought I might as well cleanup the spaces in the other type definitions while doing that. 
Also a note: I think there have been quite a few additions since the 0.1.0 tag, so maybe it would make sense to tag 0.1.1 now. (This is unrelated to this PR.)
=> Minor code formatting cleanup

queries/c/rainbow-delimiters.scm, test/highlight/c/regular.c
I noticed that the `c` queries were missing `enumerator_list`, so I added it.
=> Add missing c query

doc/rainbow-delimiters.txt, lua/rainbow-delimiters.types.lua, lua/rainbow-delimiters/lib.lua, queries/query/rainbow-blocks.scm
This PR doesn't depend on recent neovim updates, but it will be much more useful with the following:
- neovim/neovim/pull/26274 (already merged)
- neovim/neovim/pull/26304 (already merged)
I looked at #68 and thought something like that might be nice for `InspectTree`, so I added the following:
- `rainbow-blocks` for `query` (I only use this for `InspectTree`, where I think it looks nice and is helpful)
- I noticed that `priority` was typed as if it allowed a function, but the code didn't allow that, so I updated it. I also made it so we can setup the `query` with a function too (this is needed if I want `rainbow-blocks` in `InspectTree` and `rainbow-delimiters` in other `query` files). I think this adds a nice consistency too. 
- I updated the docs to reflect the above.
Note: There is …
=> Add `rainbow-blocks` to `query` and allow query setup via a function

queries/elixir/rainbow-delimiters.scm, test/highlight/elixir/regular.exs
Hi there,
Before: 
After:
Thank you again for the plugin, very nice upgrade with html / xml lately! Let me know if you need to tweak anything.
=> feat(elixir): added query for access_call

queries/c/rainbow-delimiters.scm, test/highlight/c/regular.c
I found some more missing `c` queries. I don't actually know `c` that well (I just found these while going through the neovim codebase), so I can't write tests that won't have the LSP give some complaints. Feel free to edit this, if you are more used to `c` (or suggest changes and I will update it). 
Also, there is some problem with highlighting in macros (I made a comment about it in the test file). I am not sure what is wrong there and haven't had time to look into it in more details yet.
=> Add more `c` queries

doc/rainbow-delimiters.txt, queries/javascript/rainbow-tags-react.scm, queries/tsx/rainbow-tags-react.scm
Hello and thanks for the awesome plugin! I only use it for lisp/HTML-like languages since I find the general bracket highlights a bit distracting. But I really wanted to be able to use them for the HTML parts of JSX/TSX, so I created this PR to add a query for only the React-style tags of these files, without the main highlighting. Feel free to change this PR if needed (maybe to move from the `javascript` directory to a new `jsx` directory? I wasn't sure if maybe this would add redundant queries when using an `inherits` modeline). Thanks!
=> feat: queries to highlight only jsx/tsx tags

queries/java/rainbow-delimiters.scm
#81 added some queries i was able to quickly find to enhance delimiters colorizing for `java`. I have no clue how treesitter queries work nor if they are performant so take it with the grain of salt
=> fix: add missing `java` delimiters

queries/java/rainbow-delimiters.scm
The workaround i found is to treat `dimensions` node as a single delimiter which will highlight it the same color.
One minor thing is that it will also highlight any text inside dimensions the same color as the delimiter but it's not grammatically correct anyway so it's not a big problem.
=> fix: java `dimensions` highlight

queries/rust/rainbow-delimiters.scm, test/highlight/rust/regular.rs
=> fix(rust): add missing query `array_type`

CHANGELOG.rst, autoload/rainbow_delimiters.vim, doc/rainbow-delimiters.txt, lua/rainbow-delimiters.lua, test/e2e/public-api.lua
This just adds a nice function in the API to check if rainbow delimiters are enabled in a buffer. It is currently feasible by directly requiring and accessing the internal lib functions but that seems a bit unsafe. Also was thinking if it should also check if the value isn't `nil` to see if it's actually attached. Maybe that should be a different API function (`is_attached`)? Feedback super welcome!
Also, amazing job with this project! Very much appreciate the revival of the original archived project and all of the refactors and improvements that have gotten it to where it is today :D
=> Implement functions for checking if rainbow is enabled in buffer

queries/python/rainbow-delimiters.scm, queries/starlark/rainbow-delimiters.scm, test/highlight/python/regular.py, test/highlight/starlark/regular.star
When I added `tuple_pattern` to python last time, I missed that it also applies to starlark.
Also, I found another missing python pattern `import_from_statement`, which doesn't seem to apply to starlark.
=> Add missing python and starlark queries

queries/luadoc/rainbow-delimiters.scm, test/highlight/luadoc/regular.lua
The luadoc parser was updated a couple of days ago, and I found two new queries to highlight in `rainbow-delimiters`.
=> fix(luadoc): add new luadoc queries

queries/fennel/rainbow-delimiters.scm, test/highlight/fennel/regular.fnl
Update fennel queries to be in line with the new upstream fennel parser
https://github.com/nvim-treesitter/nvim-treesitter/pull/6132
Also add commented out query for highlighting the single `:` in table bindings
=> fix(fennel)!: update queries to reflect new upstream parser

queries/java/rainbow-delimiters.scm
After some research, I find out #115 related to some treesitter deprecated syntax, and it cause a error with nvim 0.10, see this  [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/6649).
I'm not very familiar with treesitter query syntax, but by remove the `condition` block, delimiter for java work well now
=> fix(java): delimiter not work, fix #115

lua/rainbow-delimiters.types.lua, lua/rainbow-delimiters/lib.lua, lua/rainbow-delimiters/strategy/global.lua, lua/rainbow-delimiters/strategy/local.lua, lua/rainbow-delimiters/util.lua, queries/rust/rainbow-delimiters.scm, queries/wgsl/rainbow-delimiters.scm, test/highlight/rust/regular.rs, test/highlight/wgsl/regular.wgsl
Neovim has updated some type signatures, so I updated them too here. 
Also `regtype = 'c'` causes errors for me, so I changed it to `regtype = 'v'`, which seems to be what we want -- see: https://neovim.io/doc/user/builtin.html#getregtype() . I am not sure when this was changed in Neovim recently, or if this code has always been wrong? (Wrong in the sense that it maybe should have been `'v'` technically, although it definitely did accept `'c'` previously.)
(Note: I haven't yet tested this in older versions of Neovim)
Finally I added a missing rust query and wgsl support in separate commits.
=> Cleanup + missing rust query + wgsl support

queries/r/rainbow-delimiters.scm
The parser for the R language has been recently rewritten (https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/645). This PR adapt the queries for the new node names.
=> Update for the new R langage grammar

queries/c_sharp/rainbow-delimiters.scm, test/highlight/samples/c_sharp/misc.cs
Hi,
I added a capture that was missing for tuple destructuring in C#.
Let me know if anything.
Thanks again for maintaining this project!
=> fix(c_sharp): missing tuple_pattern query

queries/python/rainbow-delimiters.scm, test/highlight/samples/python/regular.py
I found a missing python query, so this is just a minor fix.
=> Add missing python query `format_expression`

queries/java/rainbow-delimiters.scm
This PR fixes Java 13's switch expressions having no highlights for their body's curly braces.
=> java: add query for switch expression body

lua/rainbow-delimiters/default.lua
Hello! In the future, it is likely that the default treesitter highlight priority will change (see https://github.com/neovim/neovim/pull/31853), which breaks this plugin. It would be nice to calculate these using `vim.highlight.priorities` (`vim.hl.priorities` on nightly). Although I am unsure how to calculate this in the vimscript example, so some help would be appreciated :) Thanks!
=> fix: calculate priority using vim.hl.priorities

doc/news.txt, queries/query/rainbow-blocks.scm, queries/query/rainbow-delimiters.scm, test/highlight/samples/query/regular.scm, test/highlight/spec/query/rainbow-blocks/regular.scm.lua, test/highlight/spec/query/rainbow-delimiters/regular.scm.lua
A new missing node syntax was added, and this commit adds support for that.
=> Update treesitter query language queries

lua/rainbow-delimiters.types.lua, queries/nu/rainbow-delimiters.scm, test/highlight/samples/nu/regular.nu
Homepage of the shell language: https://www.nushell.sh
Here I intentionally overlooked some delimiters where nested structures are not allowed by the grammar.
=> feat: add support for nushell
